apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
  labels:
    app: "hello-world"

spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: "hello-world"
  template:
    metadata:
      labels:
        app: "hello-world"
    spec:
      containers:
      - name: "hello-world"
        image: ghcr.io/vasavi269/hello-world:sha-2412939
        ports:
          - containerPort: 5000
      imagePullSecrets:
        - name: github-container-registry
---
apiVersion: v1
kind: Service
metadata:
  name: "hello-service"
spec:
  selector:
    app: "hello-world"
  type: LoadBalancer
  ports:
  - name: http
    port: 5000
    targetPort: 5000
