name: Publish Docker Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  release:
    types:
      - published
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@v2
      
      - uses: mr-smithers-excellent/docker-build-push@v4
        name: Build and push docker image
        with:
          image: vasavi269/hello-world
          registry: ghcr.io
          dockerfile: Dockerfile
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_PASSWORD }}
             
      - name: List images
        run: docker images  
        
      - name: Run a container
        run: docker run --rm -it vasavi269/hello-world

  deploy:
    name: Deploy
    needs: [build]
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set context from Kubeconfig
      uses: azure/k8s-set-context@v1
      with:
        method: kubeconfig
        kubeconfig: ${{secrets.KUBECONFIG}}
        context: quickstart-hcloud-custom
      id: setcontext

    - name: Deploy to Kubernetes
      uses: Azure/k8s-deploy@v1
      with:
        manifests: |
          deploy.yaml
        images: |
          vasavi269/hello-world