name: Publish Docker Image

on:
  push:
    tags:
      - v*
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]
  # release:
  #   types:
  #     - published
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@v2
      
      - uses: mr-smithers-excellent/docker-build-push@v4
        name: Build and push docker image
        with:
          image: vasavi269/hello-world
          registry: ghcr.io
          dockerfile: Dockerfile
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_PASSWORD }}

      # - name: Docker meta
      #   id: docker_meta
      #   uses: crazy-max/ghaction-docker-meta@v1
      #   with:
      #     images: ghcr.io/vasavi269/staging
      #     tag-sha: true
      #     tag-edge: false
      #     tag-latest: true

      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v1

      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v1

      # - name: Login to GHCR
      #   uses: docker/login-action@v1
      #   with:
      #     registry: ghcr.io
      #     username: ${{ github.repository_owner }}
      #     password: ${{ secrets.GHCR_PASSWORD }}

      # - name: Build image
      #   uses: docker/build-push-action@v2
      #   with:
      #     tags: ${{ steps.docker_meta.outputs.tags }}
      #     file: ./Dockerfile

      # - name: Push image
      #   uses: docker/build-push-action@v2
      #   with:
      #     context: .
      #     push: true
      #     tags: ${{ steps.docker_meta.outputs.tags }}
      #     file: ./Dockerfile # hello world application

  deploy:
    name: Deploy
    needs: [build]
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set context from Kubeconfig
      uses: azure/k8s-set-context@v1
      with:
        method: kubeconfig
        kubeconfig: ${{secrets.KUBECONFIG}}
        context: quickstart-hcloud-custom
      id: setcontext

    - name: Get tag name
      uses: olegtarasov/get-tag@

    - name: Get new container image tag
      id: image-tag
      run: |
        echo '::set-output name=image::ghcr.io/vasavi269/hello-world:$GIT_TAG_NAME'

    - name: Deploy to Kubernetes
      uses: Azure/k8s-deploy@v1
      with:
        manifests: |
          deploy.yaml
        images: |
          ${{ steps.image-tag.outputs.image }}