name: Publish Docker Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  release:
    types:
      - published
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      GITHUB_REPOSITORY: vasavi269
      IMAGE_NAME: hello-world
      IMAGE_TAG: ${{ github.run_number }}

    steps:
      - name: Check out
        uses: actions/checkout@v2

      # - name: Docker meta
      #   id: docker_meta
      #   uses: crazy-max/ghaction-docker-meta@v1
      #   with:
      #     images: ghcr.io/vasavi269/hello-world
      #     tag-sha: true
      #     tag-edge: false
      #     tag-latest: true

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_PASSWORD }}

      - name: Build image
        uses: docker/build-push-action@v2
        with:
          tags: $GITHUB_REPOSITORY/$IMAGE_NAME:$IMAGE_TAG
          file: ./Dockerfile

      - name: Push image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: $GITHUB_REPOSITORY/$IMAGE_NAME:$IMAGE_TAG
          file: ./Dockerfile # hello world application

  deploy:
    name: Deploy
    needs: [build]
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set context from Kubeconfig
      uses: azure/k8s-set-context@v1
      with:
        method: kubeconfig
        kubeconfig: ${{secrets.KUBECONFIG}}
        context: quickstart-hcloud-custom
      id: setcontext

    - name: set image
      uses: cschleiden/replace-tokens@v1
      with:
        files: '["deploy.yml"]'
        tokenPrefix: __
        tokenSuffix: __
      env:
        GITHUB_REPOSITORY: ${{ env.GITHUB_REPOSITORY }}
        IMAGE_NAME: ${{ env.IMAGE_NAME }}
        IMAGE_TAG: ${{ env.IMAGE_TAG }}

    - name: Deploy to Kubernetes
      uses: Azure/k8s-deploy@v1
      with:
        manifests: |
          deploy.yaml
        